default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: notes_dev

test:
  <<: *default
  database: notes_test

production:
  url: <%= ENV["DATABASE_URL"] %>